backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to masterc_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

media_folder: "static/assets"
public_folder: "assets"

collections:
  - label: data
    name: data
    files:
      - name: files
        label: Files
        file: "static/data/files.json"
        fields:
          - label: Title
            name: title
          - label: CV
            name: cv
            widget: file
          - label: Resume
            name: resume
            widget: file
      - name: projects
        label: Projects
        file: "static/data/projects.json"
        fields:
          - label: Title
            name: title
          - label: Projects
            name: projects
            widget: list
            fields:
              - label: Title
                name: title
              - label: Description
                name: description
                widget: markdown
              - label: Image
                name: image
                widget: image
              - label: Tags
                name: tags
                widget: list
              - label: File
                name: file
                widget: file
